const PERMISSIONS = {
  // Leads Module
  LEADS_VIEW: 'leads:view',
  LEADS_CREATE: 'leads:create',
  LEADS_EDIT: 'leads:edit',
  LEADS_DELETE: 'leads:delete',
  LEADS_ASSIGN: 'leads:assign',
  LEADS_EXPORT: 'leads:export',
  LEADS_IMPORT: 'leads:import',

  // Customers & Contacts
  CUSTOMERS_VIEW: 'customers:view',
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_EDIT: 'customers:edit',
  CUSTOMERS_DELETE: 'customers:delete',
  CUSTOMERS_EXPORT: 'customers:export',
  CONTACTS_VIEW: 'contacts:view',
  CONTACTS_CREATE: 'contacts:create',
  CONTACTS_EDIT: 'contacts:edit',
  CONTACTS_DELETE: 'contacts:delete',

  // Deals & Pipelines
  DEALS_VIEW: 'deals:view',
  DEALS_CREATE: 'deals:create',
  DEALS_EDIT: 'deals:edit',
  DEALS_DELETE: 'deals:delete',
  PIPELINES_VIEW: 'pipelines:view',
  PIPELINES_MANAGE: 'pipelines:manage',

  // Quotations & Invoicing
  QUOTATIONS_VIEW: 'quotations:view',
  QUOTATIONS_CREATE: 'quotations:create',
  QUOTATIONS_EDIT: 'quotations:edit',
  QUOTATIONS_DELETE: 'quotations:delete',
  QUOTATIONS_APPROVE: 'quotations:approve',
  INVOICES_VIEW: 'invoices:view',
  INVOICES_CREATE: 'invoices:create',
  INVOICES_EDIT: 'invoices:edit',
  INVOICES_DELETE: 'invoices:delete',
  PAYMENTS_VIEW: 'payments:view',
  PAYMENTS_RECORD: 'payments:record',

  // Products / Catalog
  PRODUCTS_VIEW: 'products:view',
  PRODUCTS_MANAGE: 'products:manage',

  // Tasks & Activities
  TASKS_VIEW: 'tasks:view',
  TASKS_CREATE: 'tasks:create',
  TASKS_EDIT: 'tasks:edit',
  TASKS_DELETE: 'tasks:delete',
  ACTIVITIES_VIEW: 'activities:view',
  ACTIVITIES_CREATE: 'activities:create',

  // Reports & Analytics
  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',

  // Users, Roles & Departments
  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',
  ROLES_VIEW: 'roles:view',
  ROLES_MANAGE: 'roles:manage',

  // Workspace Settings & Audit
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
  AUDIT_VIEW: 'audit:view'
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const DEFAULT_ROLE_PERMISSIONS = {
  'Super Admin': ALL_PERMISSIONS,
  'Organization Owner': ALL_PERMISSIONS,
  'Admin': ALL_PERMISSIONS.filter(p => !p.startsWith('roles:manage')),
  'Sales Manager': [
    PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CONTACTS_VIEW, PERMISSIONS.CONTACTS_CREATE, PERMISSIONS.CONTACTS_EDIT,
    PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_EDIT,
    PERMISSIONS.PIPELINES_VIEW,
    PERMISSIONS.QUOTATIONS_VIEW, PERMISSIONS.QUOTATIONS_CREATE, PERMISSIONS.QUOTATIONS_EDIT, PERMISSIONS.QUOTATIONS_APPROVE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.ACTIVITIES_VIEW, PERMISSIONS.ACTIVITIES_CREATE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_VIEW
  ],
  'Sales Executive': [
    PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CONTACTS_VIEW, PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.DEALS_VIEW, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_EDIT,
    PERMISSIONS.PIPELINES_VIEW,
    PERMISSIONS.QUOTATIONS_VIEW, PERMISSIONS.QUOTATIONS_CREATE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.ACTIVITIES_VIEW, PERMISSIONS.ACTIVITIES_CREATE
  ],
  'Support Executive': [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.ACTIVITIES_VIEW, PERMISSIONS.ACTIVITIES_CREATE
  ],
  'Accountant': [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.DEALS_VIEW,
    PERMISSIONS.QUOTATIONS_VIEW,
    PERMISSIONS.INVOICES_VIEW, PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVOICES_EDIT, PERMISSIONS.INVOICES_DELETE,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_RECORD,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT
  ],
  'Viewer': [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.DEALS_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]
};

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  DEFAULT_ROLE_PERMISSIONS
};
